name: Deploy to EC2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Use exact versions that work on your EC2 instance
        pip install numpy==1.24.4
        pip install scikit-learn==1.6.1
        pip install -r requirements.txt
        pip install pytest flake8
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    
    # - name: Run tests
    #   run: |
    #     pytest tests/
    
    - name: Train model
      run: |
        # Always retrain the model to ensure compatibility
        python train_model.py
    
    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: model-file
        path: srilanka_electricity_predictor.pkl
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download model artifact
      uses: actions/download-artifact@v4
      with:
        name: model-file
        path: ./
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        known_hosts: unnecessary
        if_key_exists: replace
    
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to EC2
      run: |
        # Create deploy directory if it doesn't exist
        ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "mkdir -p ${{ secrets.DEPLOY_PATH }}"
        
        # Copy files to EC2
        scp app.py generate_dataset.py train_model.py srilanka_electricity_dataset.csv srilanka_electricity_predictor.pkl ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:${{ secrets.DEPLOY_PATH }}/
        
        # Copy requirements file and install dependencies with proper versions
        scp requirements.txt ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:${{ secrets.DEPLOY_PATH }}/
        ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd ${{ secrets.DEPLOY_PATH }} && \
          pip3 uninstall -y numpy scikit-learn && \
          pip3 install numpy==1.24.4 scikit-learn==1.6.1 && \
          pip3 install -r requirements.txt"
        
        # Restart the application service
        ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "sudo systemctl restart electricity-predictor.service"